yarn run v1.22.10 $ tsc node_modules/@aws-sdk/node-config-provider/dist/types/fromEnv.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'. node_modules/@aws-sdk/node-config-provider/dist/types/fromEnv.d.ts(3,46): error TS2503: Cannot find namespace 'NodeJS'. node_modules/@aws-sdk/types/dist/types/eventStream.d.ts(67,19): error TS2583: Cannot find name 'AsyncIterable'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2018' or later. node_modules/@aws-sdk/types/dist/types/eventStream.d.ts(68,24): error TS2583: Cannot find name 'AsyncIterable'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2018' or later. node_modules/@aws-sdk/types/dist/types/pagination.d.ts(5,36): error TS2583: Cannot find name 'AsyncGenerator'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2018' or later. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. produces ts errors on aws-sdk declarations